#!/bin/bash

MAIN_DIR="`dirname \"$0\"`"            # relative
MAIN_DIR="`( cd \"$MAIN_DIR\" && pwd )`"  # absolutized and normalized
if [ -z "$MAIN_DIR" ] ; then
  # error; for some reason, the path is not accessible
  # to the script (e.g. permissions re-evaled after suid)
  exit 1  # fail
fi

HOME_DIR=$( getent passwd "$USER" | cut -d: -f6 )

# sources relative to MAIN_DIR
SOURCES=(
  "i3/config"
  "vim/.vimrc"
  "Xresources"
  "zsh/zshrc"
)
# destinations relative to home folder (~)
DESTINATIONS=(
  ".config/i3"
  ".vimrc"
  ".Xresources"
  ".zshrc"
)

for index in ${!SOURCES[@]}; do
  source="$MAIN_DIR/${SOURCES[$index]}"
  destination="$HOME_DIR/${DESTINATIONS[$index]}"

  # Does symlink exist?
  if [ -L $destination ]; then
    echo "$destination already exists"
  else
    ln -s $source $destination
    echo "$destination symlinked"
  fi
done
